(()=>{
const U='https://qgrsbqzhbifbyyfbslyh.supabase.co';
const K='sb_publishable_DKxNrYb1zbLkKyQQ_LAh2w_B0NRK72k';
const SK='jgos:session';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'CHF '+Number(n||0).toLocaleString('de-CH',{minimumFractionDigits:2,maximumFractionDigits:2});
let session=null,profile=null,editingCustomer=null,editingProject=null;
let data={profiles:[],requests:[],projects:[],services:[],offers:[],invoices:[],vehicles:[],mobility:[],messages:[],notifications:[],leads:[],settings:[],notes:[],documents:[]};
const staff=()=>['admin','employee'].includes(profile?.role);
const st=s=>({new:'Neu',reviewing:'Prüfung',quoted:'Offertiert',approved:'Freigegeben',in_progress:'In Umsetzung',completed:'Abgeschlossen',cancelled:'Storniert',planning:'Planung',active:'In Umsetzung',on_hold:'Pausiert',draft:'Entwurf',sent:'Versendet',accepted:'Angenommen',declined:'Abgelehnt',expired:'Abgelaufen',due:'Fällig',paid:'Bezahlt',requested:'Angefragt',confirmed:'Bestätigt',scheduled:'Geplant',locked:'Gesperrt',pending:'24h offen'}[s]||s||'—');
function headers(extra={}){const h={apikey:K,'Content-Type':'application/json',...extra};if(session?.access_token)h.Authorization='Bearer '+session.access_token;return h}
async function api(path,opt={}){const r=await fetch(U+path,{...opt,headers:headers(opt.headers||{})});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.msg||d?.error_description||t||'Fehler');return d}
function saveSession(){session?localStorage.setItem(SK,JSON.stringify(session)):localStorage.removeItem(SK)}
function visible(a){return staff()?a:a.filter(x=>x.user_id===profile.id)}
function nameOf(id){return data.profiles.find(x=>x.id===id)?.full_name||'—'}
function row(title,desc,status,actions=''){return `<div class="row"><div><div class="rn">${esc(title)}</div><div class="rd">${esc(desc)}</div></div><div class="actions"><span class="status">${esc(st(status))}</span>${actions}</div></div>`}
async function login(){const m=$('#loginMsg');m.textContent='Anmeldung …';try{session=await api('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:$('#email').value.trim(),password:$('#password').value})});saveSession();await boot()}catch(e){m.textContent=e.message}}
async function register(){const name=$('#regName').value.trim(),email=$('#regEmail').value.trim(),password=$('#regPassword').value,m=$('#loginMsg');if(!name||!email||password.length<8){m.textContent='Bitte alle Angaben ausfüllen; Passwort mindestens 8 Zeichen.';return}try{const d=await api('/auth/v1/signup',{method:'POST',body:JSON.stringify({email,password,data:{full_name:name}})});if(d?.access_token){session=d;saveSession();await boot()}else m.textContent='Konto erstellt. Bitte E-Mail bestätigen und danach anmelden.'}catch(e){m.textContent=e.message}}
async function logout(){try{await api('/auth/v1/logout',{method:'POST'})}catch{}session=null;saveSession();location.reload()}
async function getProfile(){const uid=session?.user?.id;const a=await api('/rest/v1/profiles?id=eq.'+uid+'&select=*');if(!a?.[0])throw Error('Profil nicht gefunden');return a[0]}
async function load(){const common=[['profiles','profiles?select=*&order=created_at.desc'],['requests','requests?select=*&order=created_at.desc'],['projects','projects?select=*&order=created_at.desc'],['services','service_orders?select=*&order=created_at.desc'],['offers','offers?select=*&order=created_at.desc'],['invoices','invoices?select=*&order=created_at.desc'],['vehicles','vehicles?select=*&order=name'],['mobility','mobility_bookings?select=*&order=created_at.desc'],['messages','messages?select=*&order=created_at.asc'],['notifications','notifications?select=*&order=created_at.desc&limit=100'],['settings','app_settings?select=*'],['notes','project_notes?select=*&order=created_at.asc'],['documents','documents?select=*&order=created_at.desc']];if(staff())common.push(['leads','leads?select=*&order=created_at.desc']);const results=await Promise.all(common.map(([,q])=>api('/rest/v1/'+q)));common.forEach((x,i)=>data[x[0]]=results[i]||[]);render()}
function go(v){$$('.view').forEach(x=>x.classList.remove('active'));$('#view-'+v)?.classList.add('active');$$('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#side')?.classList.remove('open')}
function render(){renderIdentity();renderDashboard();renderMyData();renderRequests();renderProjects();renderServices();renderOffers();renderInvoices();renderDocuments();renderVehicles();renderMobility();renderMessages();renderNotifications();renderLeads();renderCustomers();renderSettings();fillSelects()}
function renderIdentity(){const n=profile.full_name||session?.user?.email||'J&G Member';$('#userName').textContent=n;$('#userRole').textContent=staff()?(profile.role==='admin'?'Administrator':'Team'):(profile.membership_tier||'Member');$('#avatar').textContent=n.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();$('#hello').innerHTML=`Guten Abend, ${esc(n)} ${staff()?'<span class="adminbadge">ADMIN</span>':''}`;$$('.adminOnly').forEach(x=>x.classList.toggle('hidden',!staff()));$('#navMyData')?.classList.toggle('hidden',staff())}
function renderDashboard(){const ps=visible(data.projects),rs=visible(data.requests),os=visible(data.offers),ins=visible(data.invoices);const customers=data.profiles.filter(x=>x.role==='customer');const paid=ins.filter(x=>x.status==='paid').reduce((a,x)=>a+Number(x.total_chf||0),0);const cards=staff()?[['Offene Anfragen',rs.filter(x=>!['completed','cancelled'].includes(x.status)).length],['Aktive Projekte',ps.filter(x=>!['completed','cancelled'].includes(x.status)).length],['Offene Offerten',os.filter(x=>['draft','sent'].includes(x.status)).length],['Umsatz',money(paid)],['Kunden',customers.length],['Konten prüfen',customers.filter(x=>['pending','locked'].includes(x.account_status)).length]]:[['Anfragen',rs.length],['Projekte',ps.length],['Offerten',os.length],['Rechnungen',ins.length],['Mitgliedschaft',(profile.membership_tier||'none').toUpperCase()]];$('#kpis').innerHTML=cards.map(([a,b])=>`<div class="kpi"><div class="label">${esc(a)}</div><div class="num">${esc(b)}</div><div class="hint">Live aus J&G OS</div></div>`).join('');$('#dashProjects').innerHTML=ps.slice(0,6).map(p=>row(p.title,(staff()?nameOf(p.user_id)+' · ':'')+(p.description||''),p.status,`<button class="mini" onclick="J.openProject('${p.id}')">Öffnen</button>`)).join('')||'<div class="empty">Noch keine Projekte.</div>';$('#activities').innerHTML=[...visible(data.requests).slice(0,2).map(x=>row('Anfrage · '+x.title,'',x.status)),...visible(data.offers).slice(0,2).map(x=>row('Offerte · '+(x.offer_number||''),x.title,x.status)),...visible(data.invoices).slice(0,2).map(x=>row('Rechnung · '+(x.invoice_number||''),x.title,x.status))].join('')||'<div class="empty">Noch keine Aktivitäten.</div>';const b=$('#accountBanner');if(b&&!staff()&&profile.account_status==='pending')b.innerHTML=`<div class="notice"><b>Konto in Aktivierungsphase.</b> Qualifizierende Nutzung innerhalb von 24 Stunden aktiviert es dauerhaft.</div>`;else if(b)b.innerHTML=''}
function renderMyData(){if(!$('#mdName'))return;$('#mdName').value=profile.full_name||'';$('#mdCompany').value=profile.company||'';$('#mdPhone').value=profile.phone||'';$('#mdEmail').value=profile.email||session?.user?.email||'';$('#mdStreet').value=profile.street||'';$('#mdPostal').value=profile.postal_code||'';$('#mdCity').value=profile.city||'';$('#mdCountry').value=profile.country||'Schweiz'}
function renderRequests(){const a=visible(data.requests);$('#requestsList').innerHTML=a.map(x=>row(x.title,(staff()?nameOf(x.user_id)+' · ':'')+(x.description||''),x.status,staff()?`<button class="mini" onclick="J.reqNext('${x.id}')">Status →</button>`:'' )).join('')||'<div class="empty">Noch keine Anfragen.</div>'}
function renderProjects(){const a=visible(data.projects);$('#projectsList').innerHTML=a.map(x=>row(x.title,(staff()?nameOf(x.user_id)+' · ':'')+(x.description||''),x.status,`<button class="mini" onclick="J.openProject('${x.id}')">Projektakte</button>`)).join('')||'<div class="empty">Noch keine Projekte.</div>'}
function renderServices(){const a=visible(data.services);$('#servicesList').innerHTML=a.map(x=>row(x.service_type,(staff()?nameOf(x.user_id)+' · ':'')+(x.location||''),x.status,staff()?`<button class="mini" onclick="J.serviceNext('${x.id}')">Status →</button>`:'' )).join('')||'<div class="empty">Noch keine Serviceaufträge.</div>'}
function renderOffers(){const a=visible(data.offers);$('#offersList').innerHTML=a.map(x=>row((x.offer_number||'Entwurf')+' · '+x.title,(staff()?nameOf(x.user_id)+' · ':'')+money(x.total_chf),x.status,`<button class="mini" onclick="J.printDoc('offer','${x.id}')">Drucken</button>${staff()&&x.status==='draft'?`<button class="mini" onclick="J.offerSend('${x.id}')">Versenden</button>`:''}${!staff()&&x.status==='sent'?`<button class="mini" onclick="J.offerRespond('${x.id}','accepted')">Annehmen</button><button class="mini" onclick="J.offerRespond('${x.id}','declined')">Ablehnen</button>`:''}`)).join('')||'<div class="empty">Noch keine Offerten.</div>'}
function renderInvoices(){const a=visible(data.invoices);$('#invoicesList').innerHTML=a.map(x=>row((x.invoice_number||'Entwurf')+' · '+x.title,(staff()?nameOf(x.user_id)+' · ':'')+money(x.total_chf),x.status,`<button class="mini" onclick="J.printDoc('invoice','${x.id}')">Drucken</button>${staff()&&x.status==='draft'?`<button class="mini" onclick="J.invoiceSend('${x.id}')">Versenden</button>`:''}${staff()&&x.status!=='paid'?`<button class="mini" onclick="J.invoicePaid('${x.id}')">Bezahlt</button>`:''}`)).join('')||'<div class="empty">Noch keine Rechnungen.</div>'}
function renderDocuments(){const docs=[...visible(data.offers).map(x=>({title:(x.offer_number||'Offerte')+' · '+x.title,type:'Offerte',date:x.created_at})),...visible(data.invoices).map(x=>({title:(x.invoice_number||'Rechnung')+' · '+x.title,type:'Rechnung',date:x.created_at})),...visible(data.documents).map(x=>({title:x.title,type:x.document_type,date:x.created_at}))].sort((a,b)=>new Date(b.date)-new Date(a.date));$('#documentCount').textContent=docs.length;$('#documentsList').innerHTML=docs.map(x=>row(x.title,x.type,'archiviert')).join('')||'<div class="empty">Noch keine Dokumente.</div>'}
function renderVehicles(){$('#vehiclesGrid').innerHTML=data.vehicles.map(v=>`<div class="vehicle"><h3>${esc(v.name)}</h3><p>${esc(v.category||'J&G Mobility')} · ${esc(v.seats||'—')} Sitze</p><p>${v.on_request?'Auf Anfrage':'Verfügbar'}</p></div>`).join('')||'<div class="empty">Keine Fahrzeuge.</div>'}
function renderMobility(){$('#mobilityList').innerHTML=visible(data.mobility).map(x=>row(x.pickup+' → '+(x.destination||'offen'),new Date(x.starts_at).toLocaleString('de-CH'),x.status)).join('')||'<div class="empty">Noch keine Buchungen.</div>'}
function renderMessages(){const customer=staff()?($('#msgCustomer')?.value||data.profiles.find(x=>x.role==='customer')?.id):profile.id;const a=data.messages.filter(x=>x.user_id===customer);$('#messagesThread').innerHTML=a.map(x=>`<div class="bubble ${x.sender_id===profile.id?'me':'ai'}">${esc(x.body)}</div>`).join('')||'<div class="empty">Noch keine Nachrichten.</div>'}
function renderNotifications(){const a=(data.notifications||[]).filter(x=>staff()||x.user_id===profile.id);$('#notifCount').textContent=a.filter(x=>!x.read_at).length||'';$('#notificationsList').innerHTML=a.map(x=>row(x.title||'J&G OS',x.body||'',x.read_at?'gelesen':'neu')).join('')||'<div class="empty">Keine Benachrichtigungen.</div>'}
function renderLeads(){if(!staff()||!$('#leadsList'))return;$('#leadsList').innerHTML=data.leads.map(x=>row(x.full_name||x.email,x.message,x.status,`<button class="mini" onclick="J.lead('${x.id}','reviewing')">Prüfung</button><button class="mini" onclick="J.lead('${x.id}','qualified')">Qualifiziert</button>`)).join('')||'<div class="empty">Keine Website-Anfragen.</div>'}
function renderCustomers(){if(!staff()||!$('#customersList'))return;const a=data.profiles.filter(x=>x.role==='customer');$('#customersList').innerHTML=a.map(x=>row(x.full_name||x.email,(x.company||'')+' · '+(x.email||''),x.account_status||'active',`<button class="mini" onclick="J.customer('${x.id}')">Öffnen</button>`)).join('')||'<div class="empty">Noch keine Kunden.</div>';if(editingCustomer){const c=a.find(x=>x.id===editingCustomer);if(c){$('#customerHint').classList.add('hidden');$('#customerForm').classList.remove('hidden');$('#ceName').value=c.full_name||'';$('#ceCompany').value=c.company||'';$('#cePhone').value=c.phone||'';$('#ceEmail').value=c.email||'';$('#ceStreet').value=c.street||'';$('#cePostal').value=c.postal_code||'';$('#ceCity').value=c.city||'';$('#ceCountry').value=c.country||'Schweiz';$('#ceTier').value=c.membership_tier||'none';$('#customerAccountInfo').textContent=`Kontostatus: ${st(c.account_status||'active')}`;const rel=[...data.projects.filter(x=>x.user_id===c.id).map(x=>'Projekt: '+x.title),...data.offers.filter(x=>x.user_id===c.id).map(x=>'Offerte: '+(x.offer_number||x.title)),...data.invoices.filter(x=>x.user_id===c.id).map(x=>'Rechnung: '+(x.invoice_number||x.title))];$('#customerRelations').innerHTML='<b>Historie</b>'+ (rel.map(x=>`<div class="rd" style="margin-top:8px">${esc(x)}</div>`).join('')||'<div class="empty">Noch keine Vorgänge.</div>')}}}
function renderSettings(){if(!staff())return;const co=data.settings.find(x=>x.key==='company_profile')?.value||{},d=data.settings.find(x=>x.key==='document_defaults')?.value||{},p=data.settings.find(x=>x.key==='pricing')?.value||{};[['#coLegal','legal_name'],['#coStreet','street'],['#coPostal','postal_code'],['#coCity','city'],['#coPhone','phone'],['#coEmail','email'],['#coUid','uid'],['#coVat','vat_number'],['#coIban','iban']].forEach(([id,k])=>{if($(id))$(id).value=co[k]||''});if($('#docVat'))$('#docVat').value=d.vat_rate??8.1;if($('#docOfferDays'))$('#docOfferDays').value=d.offer_valid_days??30;if($('#docInvoiceDays'))$('#docInvoiceDays').value=d.invoice_due_days??30;if($('#docOfferFooter'))$('#docOfferFooter').value=d.offer_footer||'';if($('#docInvoiceFooter'))$('#docInvoiceFooter').value=d.invoice_footer||'';if($('#setBase'))$('#setBase').value=p.base||'';if($('#setHourly'))$('#setHourly').value=p.hourly||'';if($('#setRide'))$('#setRide').value=p.ride||'';if($('#setPerKm'))$('#setPerKm').value=p.perKm||''}
function fillSelects(){const customers=data.profiles.filter(x=>x.role==='customer'),projects=data.projects;['projectCustomer','serviceCustomer','offerCustomer','invoiceCustomer','msgCustomer'].forEach(id=>{const e=$('#'+id);if(e)e.innerHTML=customers.map(c=>`<option value="${c.id}">${esc(c.full_name||c.email)}</option>`).join('')});['serviceProject','offerProject','invoiceProject','msgProject'].forEach(id=>{const e=$('#'+id);if(e)e.innerHTML='<option value="">Ohne Projekt</option>'+projects.map(p=>`<option value="${p.id}">${esc(p.title)}</option>`).join('')});if($('#mobVehicle'))$('#mobVehicle').innerHTML=data.vehicles.map(v=>`<option value="${v.id}">${esc(v.name)}</option>`).join('')}
async function insert(table,obj){await api('/rest/v1/'+table,{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(obj)});await load()}
async function patch(table,id,obj){await api(`/rest/v1/${table}?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(obj)});await load()}
async function saveMy(){await patch('profiles',profile.id,{full_name:$('#mdName').value.trim(),company:$('#mdCompany').value.trim(),phone:$('#mdPhone').value.trim(),street:$('#mdStreet').value.trim(),postal_code:$('#mdPostal').value.trim(),city:$('#mdCity').value.trim(),country:$('#mdCountry').value.trim()});profile=await getProfile();render()}
async function createRequest(){await insert('requests',{user_id:profile.id,category:$('#reqCategory').value,title:$('#reqTitle').value.trim(),description:$('#reqDesc').value.trim()});$('#reqTitle').value='';$('#reqDesc').value=''}
async function createProject(){await insert('projects',{user_id:$('#projectCustomer').value,title:$('#projectTitle').value.trim(),budget_chf:Number($('#projectBudget').value)||null});$('#projectTitle').value=''}
async function createService(){await insert('service_orders',{user_id:$('#serviceCustomer').value,project_id:$('#serviceProject').value||null,service_type:$('#serviceType').value.trim(),location:$('#serviceLocation').value.trim(),preferred_date:$('#serviceDate').value||null,description:$('#serviceDesc').value.trim(),estimated_price_chf:Number($('#servicePrice').value)||null})}
function lineItems(prefix){const label=$('#'+prefix+'Title').value.trim();return [{label:label||'J&G Leistung',quantity:1,unit_price_chf:0,total_chf:0}]}
async function createOffer(){const user_id=$('#offerCustomer').value,title=$('#offerTitle').value.trim();if(!user_id||!title)return alert('Kunde und Titel fehlen.');await insert('offers',{user_id,project_id:$('#offerProject').value||null,title,line_items:lineItems('offer'),subtotal_chf:0,status:'draft'})}
async function createInvoice(){const user_id=$('#invoiceCustomer').value,title=$('#invoiceTitle').value.trim();if(!user_id||!title)return alert('Kunde und Titel fehlen.');await insert('invoices',{user_id,project_id:$('#invoiceProject').value||null,title,line_items:lineItems('invoice'),subtotal_chf:0,status:'draft'})}
async function createMobility(){await insert('mobility_bookings',{user_id:profile.id,vehicle_id:$('#mobVehicle').value||null,pickup:$('#mobPickup').value.trim(),destination:$('#mobDestination').value.trim(),starts_at:new Date($('#mobStart').value).toISOString(),passengers:Number($('#mobPassengers').value)||1,notes:$('#mobNotes').value.trim()})}
async function sendMessage(){const body=$('#messageInput').value.trim();if(!body)return;const user_id=staff()?($('#msgCustomer').value||null):profile.id;if(!user_id)return;await insert('messages',{user_id,sender_id:profile.id,project_id:$('#msgProject')?.value||null,body});$('#messageInput').value=''}
async function concierge(){const t=$('#chatInput').value.trim();if(!t)return;$('#chat').insertAdjacentHTML('beforeend',`<div class="bubble me">${esc(t)}</div>`);$('#chatInput').value='';try{await insert('concierge_events',{user_id:profile.id,event_type:'message',metadata:{text:t}});$('#chat').insertAdjacentHTML('beforeend','<div class="bubble ai">Ihre Concierge-Aktivität wurde sicher erfasst. Die echte KI wird mit dem Firmen-API-Konto aktiviert.</div>')}catch(e){$('#chat').insertAdjacentHTML('beforeend',`<div class="bubble ai">${esc(e.message)}</div>`)}}
async function saveCustomer(){if(!editingCustomer)return;await patch('profiles',editingCustomer,{full_name:$('#ceName').value.trim(),company:$('#ceCompany').value.trim(),phone:$('#cePhone').value.trim(),street:$('#ceStreet').value.trim(),postal_code:$('#cePostal').value.trim(),city:$('#ceCity').value.trim(),country:$('#ceCountry').value.trim(),membership_tier:$('#ceTier').value})}
async function accountStatus(s){if(!editingCustomer)return;await api('/rest/v1/rpc/admin_set_customer_account_status',{method:'POST',body:JSON.stringify({p_user_id:editingCustomer,p_status:s})});await load()}
async function saveCompany(){const v={legal_name:$('#coLegal').value.trim()||'J&G Diamant GmbH (in Gründung)',street:$('#coStreet').value.trim()||'[Strasse / Nr.]',postal_code:$('#coPostal').value.trim()||'[PLZ]',city:$('#coCity').value.trim()||'[Ort]',phone:$('#coPhone').value.trim()||'[Telefon]',email:$('#coEmail').value.trim()||'[E-Mail]',uid:$('#coUid').value.trim()||'[CHE-XXX.XXX.XXX]',vat_number:$('#coVat').value.trim()||'[MwSt.-Nr.]',iban:$('#coIban').value.trim()||'[IBAN]',country:'Schweiz'};await api('/rest/v1/app_settings?on_conflict=key',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({key:'company_profile',value:v,updated_by:profile.id})});await load()}
async function saveDocRules(){const v={vat_rate:Number($('#docVat').value)||8.1,offer_valid_days:Number($('#docOfferDays').value)||30,invoice_due_days:Number($('#docInvoiceDays').value)||30,offer_footer:$('#docOfferFooter').value.trim(),invoice_footer:$('#docInvoiceFooter').value.trim()};await api('/rest/v1/app_settings?on_conflict=key',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({key:'document_defaults',value:v,updated_by:profile.id})});await load()}
async function savePricing(){const v={base:Number($('#setBase').value)||0,hourly:Number($('#setHourly').value)||0,ride:Number($('#setRide').value)||0,perKm:Number($('#setPerKm').value)||0};await api('/rest/v1/app_settings?on_conflict=key',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({key:'pricing',value:v,updated_by:profile.id})});await load()}
function openProject(id){editingProject=id;const p=data.projects.find(x=>x.id===id);if(!p)return;$('#projectOverlay').classList.remove('hidden');$('#pmTitle').textContent=p.title;$('#pmMeta').textContent=`${nameOf(p.user_id)} · ${st(p.status)} · ${money(p.budget_chf)}`;$('#pmStatus').value=p.status;$('#pmBudget').value=p.budget_chf||'';$('#pmTarget').value=p.target_date||'';$('#pmDescription').value=p.description||'';const rel=[...data.requests.filter(x=>x.id===p.request_id).map(x=>'Anfrage: '+x.title),...data.offers.filter(x=>x.project_id===id).map(x=>'Offerte: '+(x.offer_number||x.title)),...data.invoices.filter(x=>x.project_id===id).map(x=>'Rechnung: '+(x.invoice_number||x.title)),...data.services.filter(x=>x.project_id===id).map(x=>'Service: '+x.service_type)];$('#pmRelations').innerHTML=rel.map(x=>`<div class="rd" style="margin:8px 0">${esc(x)}</div>`).join('')||'<div class="empty">Noch keine Verknüpfungen.</div>';const notes=data.notes.filter(x=>x.project_id===id);$('#pmNotes').innerHTML=notes.map(n=>`<div class="note ${n.visibility==='internal'?'internal':''}">${esc(n.body)}<div class="nd">${n.visibility==='internal'?'Intern':'Kundensichtbar'}</div></div>`).join('')||'<div class="empty">Noch keine Notizen.</div>'}
async function saveProject(){if(!editingProject)return;await patch('projects',editingProject,{status:$('#pmStatus').value,budget_chf:Number($('#pmBudget').value)||null,target_date:$('#pmTarget').value||null,description:$('#pmDescription').value.trim()});openProject(editingProject)}
async function addNote(){if(!editingProject)return;const p=data.projects.find(x=>x.id===editingProject),body=$('#pmNoteText').value.trim();if(!body)return;await insert('project_notes',{project_id:editingProject,user_id:p.user_id,author_id:profile.id,visibility:$('#pmNoteVisibility').value,body});$('#pmNoteText').value='';openProject(editingProject)}
function printDoc(kind,id){const x=(kind==='offer'?data.offers:data.invoices).find(d=>d.id===id);if(!x)return;const c=x.customer_snapshot||{},co=x.company_snapshot||{};const w=open('','_blank');w.document.write(`<!doctype html><meta charset="utf-8"><title>${esc(kind==='offer'?'Offerte':'Rechnung')}</title><style>body{font:14px Arial;margin:45px;color:#181818}h1{font-family:Georgia}.g{color:#9a7626}.top{display:flex;justify-content:space-between;border-bottom:2px solid #b89542;padding-bottom:18px}.sum{margin:30px 0 0 auto;width:300px}.sum div{display:flex;justify-content:space-between;padding:5px}</style><div class="top"><div><h1>J&G <span class="g">DIAMANT</span></h1>${esc(co.legal_name||'J&G Diamant GmbH (in Gründung)')}<br>${esc(co.street||'[Strasse]')} ${esc(co.postal_code||'[PLZ]')} ${esc(co.city||'[Ort]')}</div><b>${esc(kind==='offer'?(x.offer_number||'Offerte'):(x.invoice_number||'Rechnung'))}</b></div><p><b>${esc(c.full_name||nameOf(x.user_id))}</b><br>${esc(c.street||'')}<br>${esc((c.postal_code||'')+' '+(c.city||''))}</p><h2>${esc(x.title)}</h2><div class="sum"><div><span>Zwischensumme</span><span>${money(x.subtotal_chf)}</span></div><div><span>MwSt.</span><span>${money(x.vat_chf)}</span></div><div><b>Total</b><b>${money(x.total_chf)}</b></div></div><script>setTimeout(()=>print(),250)<\/script>`);w.document.close()}
async function boot(){profile=await getProfile();if(!staff()&&['locked','disabled'].includes(profile.account_status)){ $('#auth').classList.add('hidden');$('#lockedAccount').classList.remove('hidden');$('#lockedText').textContent=profile.account_status==='locked'?'Dieses Kundenkonto wurde nach 24 Stunden ohne qualifizierende Nutzung gesperrt.':'Dieses Kundenkonto wurde deaktiviert.';return}$('#auth').classList.add('hidden');$('#lockedAccount').classList.add('hidden');await load();go('dashboard')}
function bind(){$('#loginBtn').onclick=login;$('#registerBtn').onclick=register;$('#showRegister').onclick=()=>$('#registerBox').classList.toggle('hidden');$('#logout').onclick=logout;$('#lockedLogout').onclick=logout;$('#mobileMenu').onclick=()=>$('#side').classList.toggle('open');$$('[data-view]').forEach(x=>x.onclick=()=>go(x.dataset.view));$$('[data-go]').forEach(x=>x.onclick=()=>go(x.dataset.go));$('#saveMyData').onclick=saveMy;$('#createRequest').onclick=createRequest;$('#createProject').onclick=createProject;$('#createService').onclick=createService;$('#createOffer').onclick=createOffer;$('#createInvoice').onclick=createInvoice;$('#createMobility').onclick=createMobility;$('#messageSend').onclick=sendMessage;$('#msgCustomer')?.addEventListener('change',renderMessages);$('#chatSend').onclick=concierge;$('#saveCustomer').onclick=saveCustomer;$('#customerUnlock').onclick=()=>accountStatus('active');$('#customerLock').onclick=()=>accountStatus('locked');$('#customerDisable').onclick=()=>accountStatus('disabled');$('#saveCompany').onclick=saveCompany;$('#saveDocumentDefaults').onclick=saveDocRules;$('#saveSettings').onclick=savePricing;$('#closeProjectModal').onclick=()=>$('#projectOverlay').classList.add('hidden');$('#pmSaveProject').onclick=saveProject;$('#pmAddNote').onclick=addNote;$('#markAllRead').onclick=async()=>{for(const n of data.notifications.filter(x=>!x.read_at))await api('/rest/v1/notifications?id=eq.'+n.id,{method:'PATCH',body:JSON.stringify({read_at:new Date().toISOString()})});await load()}}
window.J={customer:id=>{editingCustomer=id;renderCustomers()},openProject,reqNext:async id=>{const x=data.requests.find(y=>y.id===id),seq=['new','reviewing','quoted','approved','in_progress','completed'];await patch('requests',id,{status:seq[Math.min(seq.indexOf(x.status)+1,seq.length-1)]})},serviceNext:async id=>{const x=data.services.find(y=>y.id===id),seq=['requested','reviewing','quoted','approved','scheduled','in_progress','completed'];await patch('service_orders',id,{status:seq[Math.min(seq.indexOf(x.status)+1,seq.length-1)]})},offerSend:id=>patch('offers',id,{status:'sent'}),invoiceSend:id=>patch('invoices',id,{status:'sent'}),invoicePaid:id=>patch('invoices',id,{status:'paid',paid_at:new Date().toISOString()}),offerRespond:async(id,decision)=>{await insert('offer_responses',{offer_id:id,user_id:profile.id,decision})},lead:(id,s)=>patch('leads',id,{status:s}),printDoc};
bind();try{session=JSON.parse(localStorage.getItem(SK)||'null')}catch{}if(session?.access_token)boot().catch(e=>{$('#loginMsg').textContent=e.message;session=null;saveSession()});
})();
