(()=>{
const U='https://qgrsbqzhbifbyyfbslyh.supabase.co';
const K='sb_publishable_DKxNrYb1zbLkKyQQ_LAh2w_B0NRK72k';
const SK='jgos:session';
const VERSION='20260825-2348';
function session(){try{return JSON.parse(localStorage.getItem(SK)||'null')}catch{return null}}
function store(s){s?localStorage.setItem(SK,JSON.stringify(s)):localStorage.removeItem(SK)}
async function refresh(s){if(!s?.refresh_token)return s;const r=await fetch(U+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:K,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:s.refresh_token}),cache:'no-store'});if(!r.ok)return s;const n=await r.json();store(n);return n}
function messageEl(btn){let m=document.querySelector('#jgosProfileSaveMsg');if(!m){m=document.createElement('div');m.id='jgosProfileSaveMsg';m.style.cssText='margin-top:12px;color:#d9bc6a;font-size:14px;line-height:1.4';btn.parentElement?.insertAdjacentElement('afterend',m)}return m}
function requestMessageEl(btn){let m=document.querySelector('#jgosRequestMsg');if(!m){m=document.createElement('div');m.id='jgosRequestMsg';m.style.cssText='margin-top:12px;color:#d9bc6a;font-size:14px;line-height:1.4';btn.insertAdjacentElement('afterend',m)}return m}
function setValue(id,v){const e=document.querySelector(id);if(e)e.value=v??''}
function applyProfile(p,s){if(!p)return;const n=p.full_name||p.email||s?.user?.email||'J&G Member';setValue('#mdName',p.full_name);setValue('#mdCompany',p.company);setValue('#mdPhone',p.phone);setValue('#mdEmail',p.email||s?.user?.email);setValue('#mdStreet',p.street);setValue('#mdPostal',p.postal_code);setValue('#mdCity',p.city);setValue('#mdCountry',p.country||'Schweiz');const name=document.querySelector('#userName');if(name)name.textContent=n;const hello=document.querySelector('#hello');if(hello)hello.textContent='Guten Abend, '+n;const avatar=document.querySelector('#avatar');if(avatar)avatar.textContent=n.split(/\s+/).filter(Boolean).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
async function saveProfile(btn){const m=messageEl(btn);m.textContent='Daten werden gespeichert …';let s=session();if(!s?.access_token||!s?.user?.id){m.textContent='Sitzung abgelaufen. Bitte erneut anmelden.';return}const body={full_name:document.querySelector('#mdName')?.value.trim()||'',company:document.querySelector('#mdCompany')?.value.trim()||'',phone:document.querySelector('#mdPhone')?.value.trim()||'',street:document.querySelector('#mdStreet')?.value.trim()||'',postal_code:document.querySelector('#mdPostal')?.value.trim()||'',city:document.querySelector('#mdCity')?.value.trim()||'',country:document.querySelector('#mdCountry')?.value.trim()||'Schweiz'};const doPatch=async()=>fetch(U+'/rest/v1/profiles?id=eq.'+encodeURIComponent(s.user.id)+'&select=*',{method:'PATCH',cache:'no-store',headers:{apikey:K,Authorization:'Bearer '+s.access_token,'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(body)});btn.disabled=true;try{let r=await doPatch();if(r.status===401){s=await refresh(s);r=await doPatch()}if(!r.ok)throw new Error((await r.text())||('HTTP '+r.status));const rows=await r.json();applyProfile(rows?.[0]||body,s);m.textContent='✓ Ihre Daten wurden gespeichert.'}catch(e){m.textContent='Speichern nicht möglich: '+e.message}finally{btn.disabled=false}}
function showRequest(row){const list=document.querySelector('#requestsList');if(!list||!row)return;const html=`<div class="row"><div><div class="rn">${String(row.title||'')}</div><div class="rd">${String(row.description||'')}</div></div><div class="actions"><span class="status">Neu</span></div></div>`;if(list.querySelector('.empty'))list.innerHTML=html;else list.insertAdjacentHTML('afterbegin',html)}
async function submitRequest(btn){const m=requestMessageEl(btn),category=document.querySelector('#reqCategory')?.value||'concierge',title=document.querySelector('#reqTitle')?.value.trim()||'',description=document.querySelector('#reqDesc')?.value.trim()||'';if(!title){m.textContent='Bitte einen Titel eingeben.';return}if(!description){m.textContent='Bitte Ihr Anliegen beschreiben.';return}let s=session();if(!s?.access_token||!s?.user?.id){m.textContent='Sitzung abgelaufen. Bitte erneut anmelden.';return}const body={user_id:s.user.id,category,title,description};const doPost=async()=>fetch(U+'/rest/v1/requests?select=*',{method:'POST',cache:'no-store',headers:{apikey:K,Authorization:'Bearer '+s.access_token,'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(body)});btn.disabled=true;m.textContent='Anfrage wird gesendet …';try{let r=await doPost();if(r.status===401){s=await refresh(s);r=await doPost()}if(!r.ok)throw new Error((await r.text())||('HTTP '+r.status));const rows=await r.json();showRequest(rows?.[0]||{...body,status:'new'});document.querySelector('#reqTitle').value='';document.querySelector('#reqDesc').value='';m.textContent='✓ Ihre Anfrage wurde erfolgreich gesendet.'}catch(e){m.textContent='Anfrage konnte nicht gesendet werden: '+e.message}finally{btn.disabled=false}}
function installProfileHotfix(){const btn=document.querySelector('#saveMyData');if(!btn||btn.dataset.jgosSaveFix==='1')return;btn.dataset.jgosSaveFix='1';btn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();saveProfile(btn)},true)}
function installRequestHotfix(){const btn=document.querySelector('#createRequest');if(!btn||btn.dataset.jgosRequestFix==='1')return;btn.dataset.jgosRequestFix='1';btn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();submitRequest(btn)},true)}
function installAdminRequestView(){const role=document.querySelector('#userRole')?.textContent.trim();if(!['Administrator','Team','CEO'].includes(role))return false;const view=document.querySelector('#view-requests');if(!view)return false;const split=view.querySelector('.split');const panels=split?[...split.querySelectorAll(':scope > .panel')]:[];if(panels[0])panels[0].style.display='none';if(split)split.style.gridTemplateColumns='1fr';const eye=view.querySelector('.eyebrow');if(eye)eye.textContent='ADMIN · SERVICE INTAKE';const title=view.querySelector('.title');if(title)title.textContent='Kundenanfragen';const sub=view.querySelector('.sub');if(sub)sub.textContent='Eingegangene Kundenanfragen prüfen, priorisieren und im Status weiterführen.';const listTitle=panels[1]?.querySelector('.ph b');if(listTitle)listTitle.textContent='Eingegangene Kundenanfragen';return true}
function installHotfixes(){installProfileHotfix();installRequestHotfix();installAdminRequestView()}
function loadScript(src,key){if(document.querySelector(`script[data-${key}]`))return;const r=document.createElement('script');r.src=src+'?v='+VERSION;r.async=false;r.setAttribute('data-'+key,'1');document.head.appendChild(r)}
loadScript('auth-recovery.js','jgos-recovery');
loadScript('admin-request-viewer.js','jgos-request-viewer');
loadScript('role-display.js','jgos-role-display');
loadScript('employee-access.js','jgos-employee-access');
loadScript('employee-access-nav-fix.js','jgos-employee-nav-fix');
loadScript('mobile-menu-close.js','jgos-mobile-menu-close');
loadScript('service-order-runtime.js','jgos-service-order-runtime');
loadScript('customer-service-fix.js','jgos-customer-service-fix');
const base=document.createElement('script');base.src='app-base.js?v='+VERSION;base.async=false;base.onload=()=>{installHotfixes();let tries=0;const timer=setInterval(()=>{tries++;if(installAdminRequestView()||tries>20)clearInterval(timer)},250);setTimeout(installHotfixes,300)};base.onerror=()=>{const m=document.querySelector('#loginMsg');if(m)m.textContent='J&G OS konnte nicht geladen werden.'};document.head.appendChild(base);
})();