(()=>{
const U='https://qgrsbqzhbifbyyfbslyh.supabase.co';
const K='sb_publishable_DKxNrYb1zbLkKyQQ_LAh2w_B0NRK72k';
const SK='jgos:session';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let session=null,vatRate=8.1;
let offerLines=[{label:'J&G Leistung',quantity:1,unit_price_chf:0}];
let invoiceLines=[{label:'J&G Leistung',quantity:1,unit_price_chf:0}];
const money=n=>'CHF '+Number(n||0).toLocaleString('de-CH',{minimumFractionDigits:2,maximumFractionDigits:2});
function loadSession(){try{session=JSON.parse(localStorage.getItem(SK)||'null')}catch{session=null}}
function headers(extra={}){const h={apikey:K,'Content-Type':'application/json',...extra};if(session?.access_token)h.Authorization='Bearer '+session.access_token;return h}
async function api(path,opt={}){const r=await fetch(U+path,{...opt,headers:headers(opt.headers||{})});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw Error(d?.message||d?.error_description||t||'Fehler');return d}
function subtotal(lines){return lines.reduce((s,l)=>s+(Number(l.quantity)||0)*(Number(l.unit_price_chf)||0),0)}
function linePayload(lines){return lines.filter(l=>String(l.label||'').trim()).map((l,i)=>({position:i+1,label:String(l.label).trim(),quantity:Number(l.quantity)||0,unit_price_chf:Number(l.unit_price_chf)||0,total_chf:(Number(l.quantity)||0)*(Number(l.unit_price_chf)||0)}))}
function render(prefix){const lines=prefix==='offer'?offerLines:invoiceLines,box=$('#'+prefix+'Lines'),total=$('#'+prefix+'DraftTotal');if(!box)return;box.innerHTML=lines.map((l,i)=>`<div class="lineItem"><input data-p="${prefix}" data-i="${i}" data-k="label" value="${String(l.label||'').replace(/"/g,'&quot;')}" placeholder="Position / Leistung"><input data-p="${prefix}" data-i="${i}" data-k="quantity" type="number" min="0" step="0.01" value="${Number(l.quantity)||0}" placeholder="Menge"><input data-p="${prefix}" data-i="${i}" data-k="unit_price_chf" type="number" min="0" step="0.05" value="${Number(l.unit_price_chf)||0}" placeholder="Einzelpreis CHF"><div class="lineTotal">${money((Number(l.quantity)||0)*(Number(l.unit_price_chf)||0))}</div><button type="button" data-remove="${prefix}" data-i="${i}">×</button></div>`).join('');const sub=subtotal(lines),vat=sub*vatRate/100;total.textContent=money(sub+vat);$$(`[data-p="${prefix}"]`).forEach(el=>el.oninput=()=>{const a=prefix==='offer'?offerLines:invoiceLines,i=Number(el.dataset.i),k=el.dataset.k;a[i][k]=k==='label'?el.value:Number(el.value)||0;render(prefix)});$$(`[data-remove="${prefix}"]`).forEach(b=>b.onclick=()=>{const a=prefix==='offer'?offerLines:invoiceLines;a.splice(Number(b.dataset.i),1);if(!a.length)a.push({label:'J&G Leistung',quantity:1,unit_price_chf:0});render(prefix)})}
function addLine(prefix){(prefix==='offer'?offerLines:invoiceLines).push({label:'',quantity:1,unit_price_chf:0});render(prefix)}
async function getVat(){try{const d=await api('/rest/v1/app_settings?key=eq.document_defaults&select=value');vatRate=Number(d?.[0]?.value?.vat_rate)||8.1}catch{}render('offer');render('invoice')}
async function saveCommercial(kind){loadSession();if(!session?.access_token)return alert('Bitte zuerst anmelden.');const p=kind==='offer'?'offer':'invoice',lines=linePayload(p==='offer'?offerLines:invoiceLines),user_id=$('#'+p+'Customer')?.value,title=$('#'+p+'Title')?.value.trim(),project_id=$('#'+p+'Project')?.value||null;if(!user_id||!title)return alert('Bitte Kunde und Titel auswählen.');if(!lines.length)return alert('Bitte mindestens eine Position erfassen.');const sub=lines.reduce((s,l)=>s+l.total_chf,0),vat=sub*vatRate/100,total=sub+vat;const body={user_id,project_id,title,line_items:lines,subtotal_chf:sub,vat_rate:vatRate,vat_chf:vat,total_chf:total,status:'draft',created_by:session.user?.id||null};await api('/rest/v1/'+(kind==='offer'?'offers':'invoices'),{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)});alert((kind==='offer'?'Offerte':'Rechnung')+' gespeichert.');location.reload()}
async function convertOffer(id){loadSession();try{await api('/rest/v1/rpc/create_invoice_from_offer',{method:'POST',body:JSON.stringify({p_offer_id:id,p_title:null})});alert('Rechnung wurde aus der angenommenen Offerte erstellt.');location.reload()}catch(e){alert(e.message)}}
function enhanceAcceptedOffers(){const list=$('#offersList');if(!list)return;[...list.querySelectorAll('.row')].forEach(r=>{const status=r.querySelector('.status')?.textContent?.trim();if(status!=='Angenommen'||r.querySelector('.convertOffer'))return;const btn=[...r.querySelectorAll('button')].find(b=>/printDoc\('offer','/.test(b.getAttribute('onclick')||''));const m=(btn?.getAttribute('onclick')||'').match(/printDoc\('offer','([^']+)'\)/);if(!m)return;const b=document.createElement('button');b.className='mini convertOffer';b.textContent='→ Rechnung';b.onclick=()=>convertOffer(m[1]);r.querySelector('.actions')?.appendChild(b)})}
function overridePrint(){if(!window.J)return;window.J.printDoc=(kind,id)=>{loadSession();api(`/rest/v1/${kind==='offer'?'offers':'invoices'}?id=eq.${id}&select=*`).then(a=>{const x=a?.[0];if(!x)return;const c=x.customer_snapshot||{},co=x.company_snapshot||{},lines=Array.isArray(x.line_items)?x.line_items:[];const w=open('','_blank');w.document.write(`<!doctype html><meta charset="utf-8"><title>${kind==='offer'?'Offerte':'Rechnung'}</title><style>body{font:14px Arial;margin:44px;color:#151515}h1,h2{font-family:Georgia}.g{color:#9a7626}.top{display:flex;justify-content:space-between;border-bottom:2px solid #b89542;padding-bottom:18px}.meta{margin:24px 0}.tbl{width:100%;border-collapse:collapse;margin-top:24px}.tbl th,.tbl td{padding:10px 8px;border-bottom:1px solid #ddd;text-align:left}.tbl th:nth-child(n+2),.tbl td:nth-child(n+2){text-align:right}.sum{margin:26px 0 0 auto;width:310px}.sum div{display:flex;justify-content:space-between;padding:6px}</style><div class="top"><div><h1>J&G <span class="g">DIAMANT</span></h1>${co.legal_name||'J&G Diamant GmbH (in Gründung)'}<br>${co.street||'[Strasse]'}<br>${co.postal_code||'[PLZ]'} ${co.city||'[Ort]'}</div><b>${kind==='offer'?(x.offer_number||'Offerte'):(x.invoice_number||'Rechnung')}</b></div><div class="meta"><b>${c.full_name||''}</b><br>${c.company||''}<br>${c.street||''}<br>${(c.postal_code||'')+' '+(c.city||'')}</div><h2>${x.title||''}</h2><table class="tbl"><thead><tr><th>Position</th><th>Menge</th><th>Einzelpreis</th><th>Total</th></tr></thead><tbody>${lines.map(l=>`<tr><td>${l.label||''}</td><td>${Number(l.quantity||0)}</td><td>${money(l.unit_price_chf)}</td><td>${money(l.total_chf)}</td></tr>`).join('')}</tbody></table><div class="sum"><div><span>Zwischensumme</span><span>${money(x.subtotal_chf)}</span></div><div><span>MwSt. ${Number(x.vat_rate||vatRate)}%</span><span>${money(x.vat_chf)}</span></div><div><b>Total</b><b>${money(x.total_chf)}</b></div></div><script>setTimeout(()=>print(),250)<\/script>`);w.document.close()}).catch(e=>alert(e.message)} }
function init(){loadSession();$('#offerAddLine')&&($('#offerAddLine').onclick=()=>addLine('offer'));$('#invoiceAddLine')&&($('#invoiceAddLine').onclick=()=>addLine('invoice'));$('#createOffer')&&($('#createOffer').onclick=()=>saveCommercial('offer'));$('#createInvoice')&&($('#createInvoice').onclick=()=>saveCommercial('invoice'));render('offer');render('invoice');getVat();overridePrint();const mo=new MutationObserver(enhanceAcceptedOffers);if($('#offersList'))mo.observe($('#offersList'),{childList:true,subtree:true});enhanceAcceptedOffers()}
init();
})();
