(()=>{
const U='https://qgrsbqzhbifbyyfbslyh.supabase.co',K='sb_publishable_DKxNrYb1zbLkKyQQ_LAh2w_B0NRK72k',SK='jgos:session';
const PERMS=[['customers','Kunden'],['requests','Anfragen'],['projects','Projekte'],['quotes','Offerten'],['service_orders','Serviceaufträge'],['invoices','Rechnungen'],['internal_messages','Interne Mitteilungen'],['vehicles','Fahrzeuge'],['documents','Dokumente'],['employees','Mitarbeiterverwaltung']];
const ROLES={management:['customers','requests','projects','quotes','service_orders','invoices','internal_messages','vehicles','documents'],administration:['customers','requests','projects','quotes','service_orders','invoices','documents'],project_manager:['customers','requests','projects','quotes','service_orders','internal_messages','documents'],dispatch:['customers','requests','projects','service_orders','vehicles'],technician:['service_orders','documents'],custom:[]};
function s(){try{return JSON.parse(localStorage.getItem(SK)||'null')}catch{return null}}function h(){return{apikey:K,Authorization:'Bearer '+(s()?.access_token||''),'Content-Type':'application/json'}}
async function q(path,opt={}){const r=await fetch(U+'/rest/v1/'+path,{...opt,headers:{...h(),...(opt.headers||{})},cache:'no-store'});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}
function role(){return document.querySelector('#userRole')?.textContent.trim()}
function ensureNav(){if(role()!=='CEO')return;const nav=document.querySelector('.nav');if(!nav||nav.querySelector('[data-view="employees"]'))return;const b=document.createElement('button');b.className='navItem';b.dataset.view='employees';b.innerHTML='<span>♙</span><span>Mitarbeiter & Rechte</span>';nav.appendChild(b);b.onclick=()=>show()}
function shell(){let v=document.querySelector('#view-employees');if(v)return v;v=document.createElement('section');v.id='view-employees';v.className='view hidden';v.innerHTML='<div class="eyebrow">CEO · ORGANISATION</div><h1 class="title">Mitarbeiter & Rechte</h1><p class="sub">Mitarbeiterzugänge verwalten, Rollen vergeben und Berechtigungen individuell steuern.</p><div class="split"><div class="panel"><div class="ph"><b>Mitarbeiter hinzufügen</b></div><div class="rd">Neue Logins werden künftig hier eingeladen. Bereits registrierte Konten können jetzt als Mitarbeiter übernommen werden.</div><select id="eaProfile" style="width:100%;margin-top:14px"></select><select id="eaRole" style="width:100%;margin-top:10px"><option value="management">Geschäftsleitung</option><option value="administration">Administration</option><option value="project_manager">Projektleitung</option><option value="dispatch">Disposition</option><option value="technician">Techniker / Monteur</option><option value="custom">Individuell</option></select><div id="eaPerms" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:8px;margin-top:14px"></div><button id="eaSave" class="btn" style="width:100%;margin-top:14px">MITARBEITER SPEICHERN</button><div id="eaMsg" class="rd" style="margin-top:10px"></div></div><div class="panel"><div class="ph"><b>Team & Zugriffsrechte</b></div><div id="eaList"></div></div></div>';document.querySelector('main')?.appendChild(v);v.querySelector('#eaRole').onchange=applyPreset;v.querySelector('#eaSave').onclick=save;return v}
function checks(){const box=document.querySelector('#eaPerms');box.innerHTML=PERMS.map(([k,l])=>`<label style="display:flex;gap:8px;align-items:center"><input type="checkbox" data-perm="${k}"> ${l}</label>`).join('')}
function applyPreset(){const set=new Set(ROLES[document.querySelector('#eaRole').value]||[]);document.querySelectorAll('[data-perm]').forEach(x=>x.checked=set.has(x.dataset.perm))}
async function load(){checks();const profiles=await q('profiles?select=id,full_name,email,role&order=full_name.asc'),access=await q('employee_access?select=*&order=created_at.asc');const used=new Set(access.map(x=>x.user_id));const sel=document.querySelector('#eaProfile');sel.innerHTML='<option value="">Konto auswählen …</option>'+profiles.filter(p=>p.role!=='ceo'&&!used.has(p.id)).map(p=>`<option value="${p.id}">${p.full_name||p.email} · ${p.email||''}</option>`).join('');const names=Object.fromEntries(profiles.map(p=>[p.id,p]));document.querySelector('#eaList').innerHTML=access.length?access.map(a=>{const p=names[a.user_id]||{};const on=Object.entries(a.permissions||{}).filter(([,v])=>v).map(([k])=>PERMS.find(x=>x[0]===k)?.[1]||k).join(', ');return `<div class="row"><div><div class="rn">${p.full_name||p.email||'Mitarbeiter'}</div><div class="rd">${a.job_role} · ${a.is_active?'Aktiv':'Deaktiviert'}<br>${on||'Keine Einzelrechte'}</div></div></div>`}).join(''):'<div class="empty">Noch keine Mitarbeiter angelegt.</div>';applyPreset()}
async function save(){const id=document.querySelector('#eaProfile').value,msg=document.querySelector('#eaMsg');if(!id){msg.textContent='Bitte zuerst ein Konto auswählen.';return}const job_role=document.querySelector('#eaRole').value,permissions={};document.querySelectorAll('[data-perm]').forEach(x=>permissions[x.dataset.perm]=x.checked);msg.textContent='Wird gespeichert …';try{await q('employee_access',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_id:id,job_role,permissions,is_active:true})});await q('profiles?id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({role:'employee'})});msg.textContent='✓ Mitarbeiter und Rechte gespeichert.';await load()}catch(e){msg.textContent='Speichern nicht möglich: '+e.message}}
async function show(){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));const v=shell();v.classList.remove('hidden');await load()}
new MutationObserver(ensureNav).observe(document.documentElement,{childList:true,subtree:true});setInterval(ensureNav,1000);ensureNav();
})();