(()=>{
const U='https://qgrsbqzhbifbyyfbslyh.supabase.co',K='sb_publishable_DKxNrYb1zbLkKyQQ_LAh2w_B0NRK72k',SK='jgos:session';
const PERMS=[['customers','Kunden'],['requests','Anfragen'],['projects','Projekte'],['quotes','Offerten'],['service_orders','Serviceaufträge'],['invoices','Rechnungen'],['internal_messages','Interne Mitteilungen'],['vehicles','Fahrzeuge'],['documents','Dokumente'],['employees','Mitarbeiterverwaltung']];
const ROLES={management:['customers','requests','projects','quotes','service_orders','invoices','internal_messages','vehicles','documents'],administration:['customers','requests','projects','quotes','service_orders','invoices','documents'],project_manager:['customers','requests','projects','quotes','service_orders','internal_messages','documents'],dispatch:['customers','requests','projects','service_orders','vehicles'],technician:['service_orders','documents'],custom:[]};
const RL={management:'Geschäftsleitung',administration:'Administration',project_manager:'Projektleitung',dispatch:'Disposition',technician:'Techniker / Monteur',custom:'Individuell'};
function s(){try{return JSON.parse(localStorage.getItem(SK)||'null')}catch{return null}}function h(){return{apikey:K,Authorization:'Bearer '+(s()?.access_token||''),'Content-Type':'application/json'}}
async function q(path,opt={}){const r=await fetch(U+'/rest/v1/'+path,{...opt,headers:{...h(),...(opt.headers||{})},cache:'no-store'});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}
function isCEO(){return document.querySelector('#userRole')?.textContent.trim()==='CEO'}
function ensureNav(){if(!isCEO())return;const nav=document.querySelector('.nav');if(!nav||nav.querySelector('[data-view="employees"]'))return;const b=document.createElement('button');b.className='navItem';b.dataset.view='employees';b.innerHTML='<span>♙</span><span>Mitarbeiter & Rechte</span>';nav.appendChild(b);b.onclick=()=>show()}
function shell(){let v=document.querySelector('#view-employees');if(v)return v;v=document.createElement('section');v.id='view-employees';v.className='view hidden';v.innerHTML=`<div class="eyebrow">CEO · ORGANISATION</div><h1 class="title">Mitarbeiter & Rechte</h1><p class="sub">Mitarbeiter einladen, Rollen vergeben und Zugriffsrechte individuell steuern.</p><div class="split"><div class="panel"><div class="ph"><b>Neuen Mitarbeiter einladen</b></div><input id="eaName" placeholder="Vor- und Nachname" style="width:100%;margin-top:8px"><input id="eaEmail" type="email" placeholder="E-Mail-Adresse" style="width:100%;margin-top:10px"><select id="eaRole" style="width:100%;margin-top:10px"><option value="management">Geschäftsleitung</option><option value="administration">Administration</option><option value="project_manager">Projektleitung</option><option value="dispatch">Disposition</option><option value="technician">Techniker / Monteur</option><option value="custom">Individuell</option></select><div id="eaPerms" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:8px;margin-top:14px"></div><button id="eaInvite" class="btn" style="width:100%;margin-top:14px">EINLADUNG SENDEN</button><div id="eaMsg" class="rd" style="margin-top:10px"></div><hr style="border:0;border-top:1px solid rgba(255,255,255,.08);margin:22px 0"><div class="ph"><b>Bereits registriertes Konto übernehmen</b></div><select id="eaProfile" style="width:100%;margin-top:10px"></select><button id="eaSave" class="btn ghost" style="width:100%;margin-top:10px">ALS MITARBEITER ÜBERNEHMEN</button></div><div class="panel"><div class="ph"><b>Team & Zugriffsrechte</b></div><div id="eaList"></div></div></div>`;document.querySelector('main')?.appendChild(v);v.querySelector('#eaRole').onchange=applyPreset;v.querySelector('#eaInvite').onclick=invite;v.querySelector('#eaSave').onclick=saveExisting;return v}
function checks(){const box=document.querySelector('#eaPerms');box.innerHTML=PERMS.map(([k,l])=>`<label style="display:flex;gap:8px;align-items:center"><input type="checkbox" data-perm="${k}"> ${l}</label>`).join('')}
function permissions(){const out={};document.querySelectorAll('[data-perm]').forEach(x=>out[x.dataset.perm]=x.checked);return out}
function applyPreset(){const set=new Set(ROLES[document.querySelector('#eaRole').value]||[]);document.querySelectorAll('[data-perm]').forEach(x=>x.checked=set.has(x.dataset.perm))}
async function load(){checks();const profiles=await q('profiles?select=id,full_name,email,role&order=full_name.asc'),access=await q('employee_access?select=*&order=created_at.asc');const used=new Set(access.map(x=>x.user_id));const sel=document.querySelector('#eaProfile');sel.innerHTML='<option value="">Konto auswählen …</option>'+profiles.filter(p=>p.role!=='ceo'&&!used.has(p.id)).map(p=>`<option value="${p.id}">${p.full_name||p.email} · ${p.email||''}</option>`).join('');const names=Object.fromEntries(profiles.map(p=>[p.id,p]));document.querySelector('#eaList').innerHTML=access.length?access.map(a=>{const p=names[a.user_id]||{};const on=Object.entries(a.permissions||{}).filter(([,v])=>v).map(([k])=>PERMS.find(x=>x[0]===k)?.[1]||k).join(', ');return `<div class="row"><div><div class="rn">${p.full_name||p.email||'Mitarbeiter'}</div><div class="rd">${RL[a.job_role]||a.job_role} · ${a.is_active?'Aktiv':'Deaktiviert'}<br>${on||'Keine Einzelrechte'}</div></div></div>`}).join(''):'<div class="empty">Noch keine Mitarbeiter angelegt.</div>';applyPreset()}
async function invite(){const btn=document.querySelector('#eaInvite'),msg=document.querySelector('#eaMsg'),email=document.querySelector('#eaEmail').value.trim(),full_name=document.querySelector('#eaName').value.trim(),job_role=document.querySelector('#eaRole').value;if(!email){msg.textContent='Bitte eine E-Mail-Adresse eingeben.';return}msg.textContent='Einladung wird gesendet …';btn.disabled=true;try{const r=await fetch(U+'/functions/v1/invite-employee',{method:'POST',headers:h(),body:JSON.stringify({email,full_name,job_role,permissions:permissions(),redirect_to:location.origin+'/app.html'})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Einladung konnte nicht gesendet werden.');document.querySelector('#eaEmail').value='';document.querySelector('#eaName').value='';msg.textContent='✓ Einladung wurde gesendet. Der Mitarbeiter kann jetzt sein Passwort setzen.';await load()}catch(e){msg.textContent='Einladung nicht möglich: '+e.message}finally{btn.disabled=false}}
async function saveExisting(){const id=document.querySelector('#eaProfile').value,msg=document.querySelector('#eaMsg');if(!id){msg.textContent='Bitte zuerst ein Konto auswählen.';return}const job_role=document.querySelector('#eaRole').value;msg.textContent='Wird gespeichert …';try{await q('employee_access',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_id:id,job_role,permissions:permissions(),is_active:true})});await q('profiles?id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({role:'employee'})});msg.textContent='✓ Mitarbeiter und Rechte gespeichert.';await load()}catch(e){msg.textContent='Speichern nicht möglich: '+e.message}}
async function show(){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));const v=shell();v.classList.remove('hidden');await load()}
new MutationObserver(ensureNav).observe(document.documentElement,{childList:true,subtree:true});setInterval(ensureNav,800);ensureNav();
})();