(()=>{
const U='https://qgrsbqzhbifbyyfbslyh.supabase.co',K='sb_publishable_DKxNrYb1zbLkKyQQ_LAh2w_B0NRK72k',SK='jgos:session',PK='jgos:pending-profile';
let syncing=false,retries=0;
function get(id){return document.getElementById(id)?.value?.trim()||''}
function capture(){const p={full_name:get('regName'),phone:get('regPhone'),street:get('regStreet'),postal_code:get('regPostal'),city:get('regCity'),country:get('regCountry')||'Schweiz',email:get('regEmail'),captured_at:new Date().toISOString()};if(p.full_name&&p.email)localStorage.setItem(PK,JSON.stringify(p))}
function read(){try{return{session:JSON.parse(localStorage.getItem(SK)||'null'),profile:JSON.parse(localStorage.getItem(PK)||'null')}}catch{return{session:null,profile:null}}}
async function sync(){if(syncing)return false;const{session:s,profile:p}=read();if(!s?.access_token||!s?.user?.id||!p)return false;syncing=true;try{const body={full_name:p.full_name||'',phone:p.phone||'',street:p.street||'',postal_code:p.postal_code||'',city:p.city||'',country:p.country||'Schweiz',email:p.email||s.user.email||''};const r=await fetch(`${U}/rest/v1/profiles?id=eq.${encodeURIComponent(s.user.id)}`,{method:'PATCH',headers:{apikey:K,Authorization:'Bearer '+s.access_token,'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(body)});if(!r.ok)throw Error(await r.text());localStorage.removeItem(PK);retries=0;window.dispatchEvent(new CustomEvent('jg:onboarding-synced',{detail:{user_id:s.user.id}}));return true}catch(e){console.warn('[J&G Onboarding] Profil-Sync ausstehend',e);return false}finally{syncing=false}}
function retry(){if(retries>=8)return;retries++;setTimeout(async()=>{const ok=await sync();if(!ok)retry()},Math.min(1200*retries,6000))}
function init(){document.getElementById('registerBtn')?.addEventListener('click',capture,true);document.getElementById('loginBtn')?.addEventListener('click',()=>setTimeout(retry,500));window.addEventListener('storage',e=>{if(e.key===SK&&e.newValue)retry()});window.addEventListener('focus',retry);setTimeout(retry,700)}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();