(()=>{
const U='https://qgrsbqzhbifbyyfbslyh.supabase.co',K='sb_publishable_DKxNrYb1zbLkKyQQ_LAh2w_B0NRK72k',SK='jgos:session';
function session(){try{return JSON.parse(localStorage.getItem(SK)||'null')}catch{return null}}
function headers(){const s=session();return{apikey:K,Authorization:'Bearer '+(s?.access_token||''),'Content-Type':'application/json'}}
async function api(path,opt={}){const r=await fetch(U+'/rest/v1/'+path,{...opt,headers:{...headers(),...(opt.headers||{})},cache:'no-store'});const t=await r.text();if(!r.ok)throw new Error(t||('HTTP '+r.status));if(!t)return null;try{return JSON.parse(t)}catch{return t}}
function role(){return document.querySelector('#userRole')?.textContent.trim()||''}
function staff(){return ['CEO','Administrator','Team'].includes(role())}
function customerUi(){const r=role();if(!r||r==='—')return;if(staff()){const w=document.querySelector('#poWorkflow');if(w)w.style.display='';return}const w=document.querySelector('#poWorkflow');if(w)w.style.display='none';const o=document.querySelector('#poOfferOverlay');if(o)o.classList.add('hidden')}
function serviceMsg(){let m=document.querySelector('#jgStableServiceMsg');if(!m){m=document.createElement('div');m.id='jgStableServiceMsg';m.className='rd';m.style.marginTop='10px';document.querySelector('#createService')?.parentElement?.insertAdjacentElement('afterend',m)}return m}
async function createService(btn){if(!staff())return;const m=serviceMsg(),user_id=document.querySelector('#serviceCustomer')?.value||'',project_id=document.querySelector('#serviceProject')?.value||null,service_type=document.querySelector('#serviceType')?.value.trim()||'',location=document.querySelector('#serviceLocation')?.value.trim()||null,preferred_date=document.querySelector('#serviceDate')?.value||null,description=document.querySelector('#serviceDesc')?.value.trim()||null,raw=document.querySelector('#servicePrice')?.value,estimated_price_chf=raw===''?null:Number(raw);if(!user_id){m.textContent='Bitte einen Kunden auswählen.';return}if(!service_type){m.textContent='Bitte eine Leistung / einen Auftrag eingeben.';return}btn.disabled=true;m.textContent='Serviceauftrag wird erstellt …';try{const rows=await api('service_orders?select=*',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({user_id,project_id,service_type,location,preferred_date,description,estimated_price_chf,status:'requested'})});const x=rows?.[0];m.textContent='✓ Serviceauftrag wurde erstellt.';const list=document.querySelector('#servicesList');if(list&&x){const row=document.createElement('div');row.className='row';row.innerHTML=`<div><div class="rn"></div><div class="rd"></div></div><div class="actions"><span class="status">Angefragt</span></div>`;row.querySelector('.rn').textContent=x.service_type||'Serviceauftrag';row.querySelector('.rd').textContent=x.location||'';if(list.querySelector('.empty'))list.innerHTML='';list.prepend(row)}}catch(e){m.textContent='Serviceauftrag konnte nicht erstellt werden: '+e.message}finally{btn.disabled=false}}
function bind(){const b=document.querySelector('#createService');if(!b||b.dataset.jgStableCreate)return;b.dataset.jgStableCreate='1';b.addEventListener('click',e=>{if(!staff())return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();createService(b)},true)}
function tick(){customerUi();bind()}
new MutationObserver(tick).observe(document.documentElement,{childList:true,subtree:true});setInterval(tick,800);tick();
})();